services:
  mongodb:
    container_name: mongodb_aboba
    image: mongo:6-jammy
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - backend

volumes:
  dbdata6:

networks:
  backend:
    driver: bridge